const roomList = [
  'Living room',
  'Bedroom',
  'Bath room',
  'Attic',
  'Kitchen',
  'Dining room',
  'Study room',
  'Home office',
  'Gaming room',
  'Outdoor pool area',
  'Outdoor patio',
  'Outdoor garden',
  'Meeting room',
  'Workshop',
  'Fitness gym',
  'Coffee shop',
  'Clothing store',
  'Walk in closet',
  'Toilet',
  'Restaurant',
  'Office',
  'Coworking space',
  'Hotel lobby',
  'Hotel room',
  'Hotel bathroom',
  'Exhibition space',
  'Onsen',
  'Mudroom',
  'Drop zone',
]

export default roomList
