const styleList = [
  'Easter',
  'Modern',
  'Minimalist',
  'Contemporary',
  'Scandinavian',
  // 'Interior AI',
  'Zen',
  'Midcentury modern',
  'Tropical',
  'Biophilic',
  'Industrial',
  'Art deco',
  'Farmhouse',
  'Rustic',
  'Bohemian',
  'Japanese design',
  'Vintage',
  'Coastal',
  'Cottagecore',
  'French country',
  'Art nouveau',
  'Cyberpunk',
  'Maximalist',
  'Gaming room',
  'Baroque',
  'Vaporwave',
  'Ski chalet',
  'Christmas',
  'Sketch',
  'Tribal',
  'Medieval',
  'Chinese New Year',
  'Halloween',
  'Neoclassic (Pro)',
]

export default styleList
