import Content from '@/components/Content/Content'
import Dialog from '@/components/Dialog/Dialog'
import Header from '@/components/Header/Header'
import Interior, { Render } from '@/components/Interior/Interior'
import NewRender from '@/components/NewRender/NewRender'
import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [newRenderOpen, setNewRenderOpen] = useState<boolean>(false)
  const [interiorCurrent, setInteriorCurrent] = useState<
    | {
        name: string
        images: {
          id: number
          img: string
          description: string
        }[]
      }
    | undefined
  >(undefined)
  const [currentRender, setCurrentRender] = useState<Render | undefined>(undefined)

  return (
    <>
      <Head>
        <title>ModernDesign AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header openNewRenderModal={() => setNewRenderOpen(true)} />
      <Content onInteriorSelect={setInteriorCurrent} onRenderSelect={setCurrentRender} />
      <Dialog fullWidth maxWidth="sm" open={newRenderOpen} onClose={() => setNewRenderOpen(false)}>
        <NewRender />
      </Dialog>
      <Dialog
        fullWidth={true}
        // fullScreen
        maxWidth={!!currentRender ? 'lg' : 'xl'}
        open={!!interiorCurrent || !!currentRender}
        onClose={() => {
          setInteriorCurrent(undefined)
          setCurrentRender(undefined)
        }}
        keepMounted={false}
      >
        <Interior currentInterior={interiorCurrent} currentRender={currentRender} setCurrentRender={setCurrentRender} />
      </Dialog>
      {/* <StyleGallery /> */}
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-B62T0MRV0M" strategy="afterInteractive" async />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-B62T0MRV0M');
        `}
      </Script>
    </>
  )
}
