import Content from '@/components/Content/Content'
import Dialog from '@/components/Dialog/Dialog'
import Header from '@/components/Header/Header'
import Interior from '@/components/Interior/Interior'
import NewRender from '@/components/NewRender/NewRender'
import Head from 'next/head'
import { useState } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [newRenderOpen, setNewRenderOpen] = useState<boolean>(false)
  const [interiorCurrent, setInteriorCurrent] = useState<
    | {
        name: string
        images: {
          id: number
          img: string
          description: string
        }[]
      }
    | undefined
  >(undefined)

  return (
    <>
      <Head>
        <title>Interior AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header openNewRenderModal={() => setNewRenderOpen(true)} />
      <Content onInteriorSelect={(interior) => setInteriorCurrent(interior)} />
      <Dialog open={newRenderOpen} onClose={() => setNewRenderOpen(false)} content={<NewRender />} />
      <Dialog
        open={!!interiorCurrent}
        onClose={() => setInteriorCurrent(undefined)}
        content={<Interior currentInterior={interiorCurrent} />}
        // fullScreen
        // // fullWidth
        // maxWidth="md"
        // sx={{
        //   '& .MuiDialog-container': {
        //     '& .MuiPaper-root': {
        //       width: '100%',
        //       maxWidth: '900px', // Set your width here
        //     },
        //   },
        // }}
        // style={{ maxWidth: '900px' }}
      />
      {/* <StyleGallery /> */}
    </>
  )
}
